# path to tabular sample information file
samples: samples.txt

# adapter sequencing for trimming
trimming:
  adapter: ACGGATCGATCGATCGATCGAT

# path to bowtie2-formatted index of host genome for read removal.
# This one is downloaded directly from NCBI.
host_reference: ref_data/GRCh38_bt2/GCA_000001405.15_GRCh38_full_analysis_set.fna.bowtie_index

# Additional command-line parameters for specific tools
params:
  cutadapt-pe: ""
  humann3: ""
  metaphlan3: ""

# Metaphlan3 DB location
metaphlan3:
  db_loc: ref_data/metaphlan3

# HUMAnN2 DB location and specifications
humann3:
  db_loc: ref_data/humann3/DEMO
  choco_db: DEMO
  uniref_db: DEMO_diamond

# Thread allocations for specific tools
threads:
  humann3: 4
  metaphlan3: 4
  host_filter: 4