# path to tabular sample information file
samples: samples.txt

# adapter sequencing for trimming
trimming:
  adapter: ACGGATCGATCGATCGATCGAT

# path to bowtie2-formatted index of host genome for read removal.
# This one is downloaded directly from NCBI.
host_reference: /local/workdir/dbs/bowtie2/Mm_GRCm39

# Additional command-line parameters for specific tools
params:
  cutadapt-pe: ""
  humann3: ""
  metaphlan3: ""

# Metaphlan3 DB location
metaphlan3:
  db_loc: /workdir/dbs/metaphlan3

# HUMAnN2 DB location and specifications
humann3:
  db_loc: /workdir/dbs/biobakery/humann_databases
  choco_db: /workdir/dbs/biobakery/humann_databases/chocophlan
  uniref_db: /workdir/dbs/biobakery/humann_databases/uniref

# Thread allocations for specific tools
threads:
  humann3: 4
  metaphlan3: 4
  host_filter: 4